### ISSUE TITLE
盖楼模式中表情依然请求http地址

### ISSUE THREAD

**Issue by tiexo** [chaclee/duoshuo-https#1]
我发现在多说盖楼模式中，引用的表情地址不会被替换

![qq 20160913103212](https://cloud.githubusercontent.com/assets/8164505/18459593/757c73b4-799d-11e6-9229-57bd432a528b.png)

如图所示，那个红脸的愤怒表情依然请求http地址

**Comment by tiexo** [comment]
貌似即便不是被引用的内容，只要回复别人，表情都有问题

![qq 20160913104018](https://cloud.githubusercontent.com/assets/8164505/18459723/8f362ea2-799e-11e6-8381-c8616d975850.png)

这个表情我用审查元素看，地址是被替换成https了
可是页面依然请求http

**Comment by chaclee** [comment]
感谢反馈，已经fix了。
原因是新浪表情域名换了导致没匹配上。
http://tp1.sinaimg.cn/=》http://img.t.sinajs.cn/

**Comment by tiexo** [comment]
@rainwsy 
感觉我误打误撞了，更新后我反馈的问题没有解决
多说平铺模式和嵌套模式都正常，就是盖楼模式不对
是不是引用的话，这个表情地址不一样？？？

**Comment by chaclee** [comment]
@tiexo 好的，我查看下

**Comment by chaclee** [comment]
@tiexo 可否提供下你这个不能显示的链接?

我这里看到已经换了，你刷新缓存duoshuo.js?v=6试看看?

![](https://dn-hb0716.qbox.me/91C713DB-C3A6-4B13-9FD6-D4DAA4E593E6.png)

**Comment by tiexo** [comment]
@rainwsy   https://www.tiexo.cn/about/

**Comment by chaclee** [comment]
@tiexo 稍等。我一会检查下

**Comment by chaclee** [comment]
@tiexo fix.盖楼嵌套的图片地址没替换，感谢。你刷新缓存下，可以在js文件后加上?v=timestamp

**Comment by tiexo** [comment]
万分感谢，问题解决了，这个项目真是太方便了！
