### ISSUE TITLE
部分weibo头像域名没覆盖

### ISSUE THREAD

**Issue by kikoroc** [chaclee/duoshuo-https#2]
十分感谢你提供的duoshuo https cdn~
使用的过程中发现部分weibo头像域名没覆盖到。
tva2.sinaimg.cn  tva3.sinaimg.cn

**Comment by chaclee** [comment]
感谢反馈，新浪最近换了几个新域名。
可否提供下地址，我晚上fix下？

**Comment by kikoroc** [comment]
我这边暂时发现两个：
//tva2.sinaimg.cn/
//tva3.sinaimg.cn/
这俩域名的头像只能http访问。
http://tva2.sinaimg.cn/crop.0.0.1080.1080.50/bae7684fjw8esagty8m3aj20u00u0mxx.jpg

**Comment by chaclee** [comment]
因为七牛限制20个bucket，把新浪这个替换到又拍云上了，现在应该是好了的。

可能有缓存，你尝试在duoshuo.js后加时间戳参数看看

**Comment by kikoroc** [comment]
恩，可以了。👍
